name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@7709f4bd34c4e32c689572005775ae6834ae4a1a # (latest, untagged)
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
