name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@60a9f1aab8d0254fae9b295420ee36ed324632e1 # (latest, untagged)
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
