name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@ad9853fd5ccf446babb7f0ed95f79fea2cd5f8ee # (latest, untagged)
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
