name: 'Auto Author Assign'
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@0fd2847dd52b3cb103d743049dcfb7f17d39c51f # (latest, untagged)
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
