name: "Pull Request Labeler"
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@83720bce8638d1b5b7b15ae76465522ca7ea2eec # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
