name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@a76cf44ddb1ab997b52718d59b0efc8adc55cf5c # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
