name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bb8a4df92471ecece5a2667815a51b34d3bc90ae # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
