name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@6c834e41a82952bc67e003a8b2854840c337556e # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
