name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@e5bd0679301f48c2e2027f7b010fec2b1132ef77 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
