name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@59718b0b66a52e0ca224d43760b84cca3804c63a # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
