name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@6fe667229698f2d6feb1973d9ef966606cbe9cb6 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
