name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@17086b774338d2689ada0d8fcc8c51b5c9bc782a # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
