name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@5bb656d641ca1a3c88a6732b1772371d4640cfdf # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
