name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@3cc2196fe8a6d764cd07de658ad43a93ad8cd8d1 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
