name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@0807891f38bff14bfd6fde451cf17173ba0c2570 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
