name: "Pull Request Labeler"
on:
  pull_request_target:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@2b2e7d04cb1a6ea65c273238d0e516840a7a380e # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
