name: "Pull Request Labeler"
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@506e1a00c6c05ba98ac585056a23f16073fa5915 # (latest, untagged)
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
